version: "3.3"

services:
  DB:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    volumes:
    - ./my_dbdata:/var/lib/postgresql/data

    environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
  node-app:
    build: .
    env_file: .dev.env
    ports:
      - 3001:3001